#
#
# This plugin was specifically made for Ogredupe.minehut.gg
# Author: ImproperIssues
# Owner: TheTelly
# Date Created: 1/15/2023
#
# This plugin is in BETA and more features will be added in the future.
#
#
config:
  plugin:
    prefix: '§7[§3Ogre§5Dupe§7] §r'
    specific-commands: false
    op-bypass-plugin-restrictions: false
  custom:
    sieving: true
  combat:
    anti-nakedkill: true
  chat:
    anti-spam: true
    chat-cooldown: 1000
    anti-swear: true
    anti-unicode: true
    anti-swear-notify-permission: 'ogredupealias.chat.see'
    blacklist:
      - 'example-word1'
      - 'example-word2'
      - 'example-word3'
    blacklist-override:
      - 'example-word1'
      - 'example-word2'
      - 'example-word3'
    anti-command-spam: true
    command-cooldown: 1000
    command-cooldown-list:
      - '/me'
      - '/say'
      - '/tp'
      - '/tpa'
      - '/tpahere'
  messages:
    swear: "§cPlease do not swear in chat!"
    spam: "§cPlease wait a moment before doing this again!"
    repeat: "§cPlease do not repeat the same message!"
    plugin-specific: "§cPlugin-specific commands aren't allowed on this server!"
    disabled: "§cThe chat is disabled at the moment!"
    unicode: "§cYour message contains characters that are not supported on this server!"
    player-firstjoin: '§e%player% joined for their first time' #Tip: Use %player% for player's name
    player-join: '§e%player% joined the game' #Tip: Use %player% for player's name
    player-quit: '§e%player% left the game' #Tip: Use %player% for player's name
  socialspy:
    commandspy-blacklist:
      - '/dupe'
      - '/msg'
      - '/w'
      - '/private-message'
      - '/pm'
      - '/message'
      - 'whisper'
      - '/tell'
